### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by mben42** [LukeOnuke/AdminTools#4]
Hello,

I have this error when starting Spigot:

```[16:35:24] [Server thread/ERROR]: Could not load 'plugins/AdminTools.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.16.3.jar:git-Spigot-988b411-2a3ca13]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-1.16.3.jar:git-Spigot-988b411-2a3ca13]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.3.jar:git-Spigot-988b411-2a3ca13]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:183) ~[spigot-1.16.3.jar:git-Spigot-988b411-2a3ca13]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.3.jar:git-Spigot-988b411-2a3ca13]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-988b411-2a3ca13]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more
```

Thanks in advance.

**Comment by LukeOnuke** [comment]
**Good day / morning / evening,**

AdminTools is a standalone program that runs by itself. Its not a plugin.

AdminTools uses the [RCON protocol](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol) to connect with a server  remotely. 
Once ill setup the atdocs but for now : 
 ### Setting up RCON

1. Find the `server properties file `
2. Find these valiues and set them accordingly
    ```
   enable-rcon=true
    rcon.password=<your password>
    rcon.port=<1-65535> (if its already set then don't change it)
    broadcast-rcon-to-ops=false
    ```

Hope this helps
